USE [master]
GO

/****** Object:  Database [A_Resturant]    Script Date: 14/09/2022 06:01:12 PM ******/
CREATE DATABASE [A_Resturant]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'A_Resturant', FILENAME = N'D:\data\A_Resturant.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'A_Resturant_log', FILENAME = N'D:\data\A_Resturant_log.ldf' , SIZE = 1600KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [A_Resturant] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [A_Resturant].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [A_Resturant] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [A_Resturant] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [A_Resturant] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [A_Resturant] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [A_Resturant] SET ARITHABORT OFF 
GO

ALTER DATABASE [A_Resturant] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [A_Resturant] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [A_Resturant] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [A_Resturant] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [A_Resturant] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [A_Resturant] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [A_Resturant] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [A_Resturant] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [A_Resturant] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [A_Resturant] SET  DISABLE_BROKER 
GO

ALTER DATABASE [A_Resturant] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [A_Resturant] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [A_Resturant] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [A_Resturant] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [A_Resturant] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [A_Resturant] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [A_Resturant] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [A_Resturant] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [A_Resturant] SET  MULTI_USER 
GO

ALTER DATABASE [A_Resturant] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [A_Resturant] SET DB_CHAINING OFF 
GO

ALTER DATABASE [A_Resturant] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [A_Resturant] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [A_Resturant] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [A_Resturant] SET  READ_WRITE 
GO


